[package]
name = "scan_portal"
version = "0.1.0"
edition = "2021"
author = "ziggoon"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ftp = "3.0.1"
rustyline = "7.1.0"
colored = "2.0.0"
